"""some changes

Revision ID: 8a6b4bd66fa1
Revises: f6b312919300
Create Date: 2023-12-16 22:06:12.291933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a6b4bd66fa1"
down_revision: Union[str, None] = "f6b312919300"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "commands", sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("commands", "executed_at")
    # ### end Alembic commands ###
