"""add channel id and message id to command

Revision ID: e22baa436a27
Revises: 61a59f417a92
Create Date: 2023-12-30 12:29:27.576916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e22baa436a27'
down_revision: Union[str, None] = '61a59f417a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commands', sa.Column('channel_id', sa.TEXT(), nullable=True))
    op.add_column('commands', sa.Column('message_id', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commands', 'message_id')
    op.drop_column('commands', 'channel_id')
    # ### end Alembic commands ###
